'use client';
import { LegalPage } from '../../components/legal/LegalPage';
import { legalP, legalH2, legalLi } from '../../lib/legalStyles';

export function TermsClient() {
  return (
    <LegalPage
      eyebrow="Terms"
      title="Terms of Use"
      updated="2 September 2026"
      intro="The rules for using drivelink.tech, and what the claims, figures, and simulations on it do and do not mean."
    >
      <p style={legalP}>
        The website at <strong>drivelink.tech</strong> (including <strong>www.drivelink.tech</strong> and{' '}
        <strong>core.drivelink.tech</strong>) is operated by DriveLink Technologies, Bengaluru, Karnataka, India
        (&ldquo;DriveLink&rdquo;, &ldquo;we&rdquo;). By using the site you agree to these terms. If you do not agree,
        please do not use it.
      </p>

      <h2 style={legalH2}>1. What this site is</h2>
      <p style={legalP}>
        It is an informational site about a V2V communication protocol under development. It is not a product you can
        buy, an offer to sell securities, investment advice, or a safety system you may rely on. Nothing here creates
        a contract, a partnership, or an obligation on either side.
      </p>

      <h2 style={legalH2}>2. Simulations and figures</h2>
      <p style={legalP}>
        The traffic animations on the home and product pages are <strong>concept simulations</strong> that run
        entirely in your browser. The vehicles, links, and latency readouts they display are generated by that model —
        they are not live telemetry, and they do not report on any deployed vehicle or network.
      </p>
      <p style={legalP}>
        Performance numbers stated on the site (including sub-50ms end-to-end latency, payload size, and prediction
        window) are <strong>design targets from the drv-mesh v0.1 specification</strong>, not measured field results.
        Roadmap dates are intentions, not commitments. Where the site describes an award — including the Patent Grant
        Option received at a national hackathon — it describes that award only; DriveLink does not claim a granted
        patent.
      </p>

      <h2 style={legalH2}>3. The assistant</h2>
      <p style={legalP}>
        The on-site assistant is generated by a language model and can be wrong. Treat its answers as a convenience,
        not as a statement by DriveLink, and confirm anything that matters with us by email. Do not use it to submit
        confidential information, and do not attempt to overload or abuse the endpoint — it is rate limited.
      </p>

      <h2 style={legalH2}>4. Acceptable use</h2>
      <ul>
        <li style={legalLi}>Do not attempt to breach, probe, or disrupt the site or its underlying services.</li>
        <li style={legalLi}>Do not scrape it at a volume that degrades it for others.</li>
        <li style={legalLi}>Do not submit false information, impersonate anyone, or upload malware through any form.</li>
        <li style={legalLi}>Do not use the site or its content to imply an endorsement or partnership that does not exist.</li>
      </ul>

      <h2 style={legalH2}>5. Intellectual property</h2>
      <p style={legalP}>
        The site&apos;s text, design, diagrams, and marks are ours or our licensors&apos;, and you may not reproduce
        them commercially without permission. Quoting or linking to the site with attribution is fine. Source code we
        publish on GitHub is governed by the licence in each repository, not by these terms.
      </p>
      <p style={legalP}>
        DriveLink is unaffiliated with Toyota Connected&apos;s &ldquo;Drivelink&rdquo; telematics platform, or with any
        other company using a similar name. Third-party names and marks that appear on the site belong to their
        respective owners and are used only to identify them.
      </p>

      <h2 style={legalH2}>6. External links</h2>
      <p style={legalP}>
        The site links to third-party sites we do not control and are not responsible for.
      </p>

      <h2 style={legalH2}>7. Disclaimer and liability</h2>
      <p style={legalP}>
        The site is provided &ldquo;as is&rdquo;, without warranties of any kind, and we do not promise it will be
        accurate, complete, current, or uninterrupted. To the fullest extent the law allows, DriveLink is not liable
        for any indirect or consequential loss arising from your use of the site or reliance on anything published on
        it. Nothing here limits liability that cannot lawfully be limited.
      </p>

      <h2 style={legalH2}>8. Changes and governing law</h2>
      <p style={legalP}>
        We may update these terms; the date at the top of this page changes when we do, and continued use means you
        accept the update. These terms are governed by the laws of India, and the courts of Bengaluru, Karnataka have
        exclusive jurisdiction. Questions:{' '}
        <a href="mailto:tech.drivelink@gmail.com?subject=Terms%20enquiry">tech.drivelink@gmail.com</a>.
      </p>
    </LegalPage>
  );
}
